### ISSUE TITLE
Lua error in search

### ISSUE THREAD

**Issue by credomane** [MrDoomah/What-is-it-used-for-#1]
To reproduce:
1. CTRL+F to open search window
2. Type in "oil".
3. Wait for major lag if you are BAY life. (Bob + Angel + Yuoki)
4. CTRL+F to hide search window.
5. Click search result.
6. LUA error.

Search results should probably get hidden when hiding the search bar as that is what I was attempting to do when I caused this error.

**Comment by MrDoomah** [comment]
This doesn't depend on the lag, it happens any time you close the search bar while the results are displayed, #4 indeed is how it was supposed to work.
